### PR TITLE
checkInactivity: Add inactive state. Fixes #69.

### LINKED ISSUE #69: Inactive feature: zulipbot leaves issue/PR alone if it has a specific label
@zulipbot label "new feature" "enhancement"

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by lonerz** [comment]
@synicalsyntax can you give this a review?

**Comment by lonerz** [comment]
@synicalsyntax can you give this another look?

**Comment by lonerz** [comment]
@synicalsyntax does `return` act like a `continue` in a foreach loop?

**Comment by synicalsyntax** [comment]
`return` would return a specific value to the function that called it instead.

**Pull request closed without merging**
